<a href="https://colab.research.google.com/github/jamesmuiru/ArcGIS_maxent_datapreparation_code/blob/main/Linear_regression_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression with California Housing Dataset

This notebook demonstrates a linear regression analysis using the California Housing dataset. We will cover the following steps:

1.  **Import Libraries**: Loading necessary Python libraries.
2.  **Load Data**: Fetching and understanding the California Housing dataset.
3.  **Data Preparation**: Splitting the dataset into training and testing sets.
4.  **Model Training**: Training a Linear Regression model using scikit-learn.
5.  **Model Evaluation**: Assessing the model's performance using various metrics.
6.  **Normal Equation Comparison**: Comparing the scikit-learn model with a direct implementation of the Normal Equation.

## 1. Import Libraries

We begin by importing the essential libraries for data manipulation, numerical operations, plotting, and machine learning.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import datasets

## 2. Load Data

We will load the California Housing dataset, a popular dataset for regression tasks, available through `sklearn.datasets`. The dataset contains information about housing in various districts of California.

In [ ]:
from sklearn.datasets import fetch_california_housing

# Load the California housing dataset
california_housing = fetch_california_housing(as_frame=True)

# Display a description of the dataset
print(california_housing.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per census
block group. A block group is the smallest geographical unit for which the U.S.
Census Bureau publishes sample data (a block group typically has a population
of 600 to 3,000 people).

A household is a group of people residing within a home. Since the average
number of rooms and bedrooms in this dataset are provided per household, these
columns may take surprisingly large values for block groups with few households
and many empty houses, such as vacation resorts.

It can be downloaded/loaded using the
:func:`sklearn.datasets.fetch_california_housing` function.

.. rubric:: References

- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,
  Statistics and Probability Letters, 33 (1997) 291-297

The `california_housing.data` DataFrame contains the features, and `california_housing.target` contains the target variable (median house value). Let's display the first few rows of both to get an idea of the data structure.

## 3. Data Preparation

Before training our model, we need to prepare the data by splitting it into training and testing sets. This allows us to train the model on one subset of data and evaluate its performance on unseen data.

In [ ]:
print("Features:")
display(california_housing.data.head())

print("Target:")
display(california_housing.target.head())

Features:

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

Target:

0    4.526
1    3.585
2    3.521
3    3.413
4    3.422
Name: MedHouseVal, dtype: float64

### Split the dataset into training and testing sets

We will use `sklearn.model_selection.train_test_split` to divide the dataset. It's good practice to separate features (`X`) and the target variable (`y`) first.

In [ ]:
from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = california_housing.data
y = california_housing.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (16512, 8)
Shape of X_test: (4128, 8)
Shape of y_train: (16512,)
Shape of y_test: (4128,)

## 4. Model Training

Now, we'll train a Linear Regression model using the training data (`X_train`, `y_train`) from the scikit-learn library. After training, we'll print the learned coefficients and the intercept of the model.

### Train a Linear Regression Model

Now, let's train a `LinearRegression` model using the training data.

In [ ]:
from sklearn.linear_model import LinearRegression

# Instantiate the Linear Regression model
model = LinearRegression()

# Train the model using the training data
model.fit(X_train, y_train)

print("Model Coefficients (features weights):")
print(model.coef_)
print("\nModel Intercept (bias):")
print(model.intercept_)

Model Coefficients (features weights):
[ 4.48674910e-01  9.72425752e-03 -1.23323343e-01  7.83144907e-01
 -2.02962058e-06 -3.52631849e-03 -4.19792487e-01 -4.33708065e-01]

Model Intercept (bias):
-37.02327770606409

## 5. Model Evaluation

After training, it's crucial to evaluate how well our model performs on unseen data. We will use the test set (`X_test`, `y_test`) and common regression metrics to assess the model's accuracy.

### Evaluate the Model Performance

Now, let's evaluate the performance of our trained Linear Regression model using the test data (`X_test`, `y_test`). We will use several common metrics:

*   **Mean Absolute Error (MAE)**: The average of the absolute errors. It's a measure of the average magnitude of the errors in a set of predictions, without considering their direction. It is the average over the test sample of the absolute differences between prediction and actual observation where all individual differences have equal weight.

*   **Mean Squared Error (MSE)**: The average of the squared errors. It penalizes larger errors more heavily than MAE, as the errors are squared. It is always non-negative, and a value closer to zero is better.

*   **R-squared (R²)**: Represents the proportion of the variance in the dependent variable that is predictable from the independent variables. An R-squared of 1 indicates that the regression predictions perfectly fit the data, while 0 indicates that the model explains no variability in the response variable around its mean.

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R²): {r2:.2f}")

Mean Absolute Error (MAE): 0.53
Mean Squared Error (MSE): 0.56
R-squared (R²): 0.58

## 6. Normal Equation Comparison

In this section, we'll implement the Normal Equation from scratch to calculate the linear regression coefficients directly and compare them with the coefficients obtained from the `sklearn.linear_model.LinearRegression` model. The Normal Equation provides a closed-form solution for the weights ($w$) that minimize the cost function.

The Normal Equation is given by:

$$w = (X^T X)^{-1} X^T y$$

Where:
*   $X$: Feature Matrix
*   $X^T$: Transpose of the Feature Matrix
*   $(X^T X)^{-1}$: Inverse of $(X^T X)$
*   $y$: Target Vector
*   $w$: Weights (coefficients) of the model

To ensure a fair comparison with scikit-learn's `LinearRegression`, which inherently handles an intercept, we will augment our feature matrix `X` with a column of ones. This allows the Normal Equation to calculate both the coefficients for each feature and the intercept term.

## Normal Equation for Linear Regression

The **Normal Equation** is a closed-form solution to find the value of $w$ that minimizes the cost function:

$$w = (X^T X)^{-1} X^T y$$

---

### Let’s connect code to math
* **`X.T`** = Transpose ($X^T$)
* **`@`** = Matrix multiplication
* **`np.linalg.inv()`** = Inverse matrix ($^{-1}$)

---

### Meaning of each part

| Symbol | Name | Description |
| :--- | :--- | :--- |
| $X$ | **Feature Matrix** | Input data (samples $\times$ features). |
| $X^T$ | **Transpose** | Flips the matrix rows and columns. |
| $(X^T X)^{-1}$ | **Inverse Matrix** | The inverse of the Gram matrix. |
| $y$ | **Target Vector** | The actual values we want to predict. |
| $w$ | **Weights** | The learned parameters (coefficients). |

First, let's recalculate the weights using the Normal Equation, ensuring we augment our `X_train` matrix with an intercept term. Then, we will compare these calculated coefficients and intercept with those from the `sklearn` model.

In [ ]:
weights=np.linalg.inv(X_train.T @ X_train) @ X_train.T @ y_train
print(weights)

0    0.522530
1    0.015893
2   -0.193890
3    0.975498
4    0.000009
5   -0.004404
6   -0.062165
7   -0.014985
dtype: float64

In [ ]:
model.coef_

array([ 4.48674910e-01,  9.72425752e-03, -1.23323343e-01,  7.83144907e-01,
       -2.02962058e-06, -3.52631849e-03, -4.19792487e-01, -4.33708065e-01])

In [ ]:
difference=weights-model.coef_
print(difference)

0    0.073855
1    0.006168
2   -0.070566
3    0.192353
4    0.000011
5   -0.000878
6    0.357628
7    0.418723
dtype: float64

In [ ]:
# calculate the correlation between the weights
np.corrcoef(weights, model.coef_)

array([[1.        , 0.89875888],
       [0.89875888, 1.        ]])

In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_california_housing
from sklearn.linear_model import LinearRegression # Added for model definition

# Ensure california_housing is loaded
if 'california_housing' not in globals(): # Use globals() for top-level variables
    print("Loading California Housing dataset...")
    california_housing = fetch_california_housing(as_frame=True)

# Define features (X) and target (y)
X = california_housing.data
y = california_housing.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Ensure the sklearn model is trained
if 'model' not in globals() or not isinstance(model, LinearRegression): # Check if model is defined and is a LinearRegression instance
    print("Training sklearn Linear Regression model...")
    model = LinearRegression()
    model.fit(X_train, y_train)

# Augment X_train and X_test with a column of ones for the intercept
# This ensures the Normal Equation can also calculate an intercept term
X_train_augmented = np.c_[np.ones(X_train.shape[0]), X_train]
X_test_augmented = np.c_[np.ones(X_test.shape[0]), X_test]

# Recalculate weights using the Normal Equation with the augmented X_train
# The first element of weights_normal_eq_full will be the intercept, and the rest will be coefficients
weights_normal_eq_full = np.linalg.inv(X_train_augmented.T @ X_train_augmented) @ X_train_augmented.T @ y_train

# Separate intercept and coefficients from the Normal Equation result
intercept_normal_eq = weights_normal_eq_full[0]
coef_normal_eq = weights_normal_eq_full[1:]

print("Normal Equation Coefficients (with intercept):")
print(coef_normal_eq)
print("\nNormal Equation Intercept:")
print(intercept_normal_eq)

print("\nSklearn Model Coefficients:")
print(model.coef_)
print("\nSklearn Model Intercept:")
print(model.intercept_)

# Make predictions using the Normal Equation (with intercept) on the test set
y_pred_normal_eq = X_test_augmented @ weights_normal_eq_full

# Calculate evaluation metrics for the Normal Equation predictions
mae_normal_eq = mean_absolute_error(y_test, y_pred_normal_eq)
mse_normal_eq = mean_squared_error(y_test, y_pred_normal_eq)
r2_normal_eq = r2_score(y_test, y_pred_normal_eq)

print(f"\n--- Model Performance Comparison on Test Set ---")
print(f"\nNormal Equation (with intercept) - Mean Absolute Error (MAE): {mae_normal_eq:.2f}")
print(f"Normal Equation (with intercept) - Mean Squared Error (MSE): {mse_normal_eq:.2f}")
print(f"Normal Equation (with intercept) - R-squared (R²): {r2_normal_eq:.2f}")

print(f"\nSklearn Model - Mean Absolute Error (MAE): {mae:.2f}")
print(f"Sklearn Model - Mean Squared Error (MSE): {mse:.2f}")
print(f"Sklearn Model - R-squared (R²): {r2:.2f}")

Normal Equation Coefficients (with intercept):
[ 4.48674910e-01  9.72425752e-03 -1.23323343e-01  7.83144907e-01
 -2.02962058e-06 -3.52631849e-03 -4.19792487e-01 -4.33708065e-01]

Normal Equation Intercept:
-37.02327770618458

Sklearn Model Coefficients:
[ 4.48674910e-01  9.72425752e-03 -1.23323343e-01  7.83144907e-01
 -2.02962058e-06 -3.52631849e-03 -4.19792487e-01 -4.33708065e-01]

Sklearn Model Intercept:
-37.02327770606409

--- Model Performance Comparison on Test Set ---

Normal Equation (with intercept) - Mean Absolute Error (MAE): 0.53
Normal Equation (with intercept) - Mean Squared Error (MSE): 0.56
Normal Equation (with intercept) - R-squared (R²): 0.58

Sklearn Model - Mean Absolute Error (MAE): 0.53
Sklearn Model - Mean Squared Error (MSE): 0.56
Sklearn Model - R-squared (R²): 0.58

The results show that the coefficients and intercept calculated by the Normal Equation are nearly identical to those obtained from `sklearn.linear_model.LinearRegression`. Furthermore, the evaluation metrics (MAE, MSE, R²) for predictions made using both methods are also effectively the same. This confirms that both approaches find the same optimal parameters for the linear regression model.